### ISSUE TITLE
Hypercore replication in browser fails

### ISSUE THREAD

**Issue by Nazeh** [hyperswarm/dht-relay#7]
I tested the `dht-relay` extensively, and while `announce`, `lookup`, `server.listen` and `connect` works just fine, trying to replicate a Hypercore throws an error (only in browser environment): 

```js
Error: Noise handshake failed
    at NoiseSecretStream._onhandshakert (bundle.js:1993)
    at NoiseSecretStream._open (bundle.js:2041)
    at WritableState.updateNonPrimary (bundle.js:16661)
    at WritableState.update (bundle.js:16639)
    at WritableState.updateWriteNT (bundle.js:16947)
```

I tracked this issue and figured that `this.protocol.connect(message)` eventually returns `undefined` even though the content of the `message` is valid, and even though the server node seems to perform the handshake correctly.

I got the same result whether I am testing this in an actual application, or in more controlled test suite https://github.com/synonymdev/dht-universal/blob/5fc36d4e21ab0a04dd4bf0e64a9e9816492d941a/test/api.spec.js#L439

**Comment by Nazeh** [comment]
Maybe this issue is more relevant in [Hypercore](https://github.com/hypercore-protocol/hypercore-next) instead, but I confirmed that the replicating using the `dht-relay` only fails in the browser, not nodejs.

**Comment by Nazeh** [comment]
Isolated test https://github.com/Nazeh/test-hypercore-dht-relay

**Comment by RangerMauve** [comment]
What are you using to compile the code for the browser? I've had issues getting Webpack to work because the node globals that it injects are out of date.

I've found that browserify is the only surefire path to get it working. 😅

**Comment by Nazeh** [comment]
@RangerMauve 
I tested both with [aegir](https://github.com/ipfs/aegir) (esbuild) and Parcel. I will test with Browserify similar to how `hyper-sdk` does it and report back.

**Comment by Nazeh** [comment]
Tested again with [browserify](https://github.com/Nazeh/test-hypercore-dht-relay), same result.

**Comment by Nazeh** [comment]
Fwiw I tested [again](https://github.com/Nazeh/test-hypercore-dht-relay/blob/master/package.json#L18) using the latest change in the master branch

**Comment by kasperisager** [comment]
Thanks for the report and reproduction! I'll investigate this today and am already seeing some possibly related bugs after my work in #5 and #8.

**Comment by kasperisager** [comment]
With d2ff078a4a4e264272c43e79c12e98d7b13a9f73 in place, I have Hypercore replication working in a browser between two relayed peers, i.e. both running in the browser and connected through the relay.

**Comment by Nazeh** [comment]
@kasperisager looks great, but I tried the new API [here](https://github.com/Nazeh/test-hypercore-dht-relay/commit/17f03028ee5416a383c388d73194e406b5249b47) and the replication between the browser (initiator) and the Nodejs side as (responder) is still throwing the same error.

I will try to test the other way too in case it offers any insight!

**Comment by mafintosh** [comment]
@Nazeh you should change that to use the core.replicate(swarmStream) api, otherwise you’ll be double encrypting

that’s prob why it fails, there is a method missing in sodium for encryption

**Comment by mafintosh** [comment]
… in the browser

**Comment by Nazeh** [comment]
@mafintosh Indeed, it works with Hyperswarm in the browser, ... after adding `b4a` to Hyperswarm

**Comment by kasperisager** [comment]
Let me know if https://github.com/hyperswarm/hyperswarm/pull/98 does the trick.

**Comment by Nazeh** [comment]
@kasperisager Unfortunately no, that PR introduced a dependency that needs `Buffer` ( `turbo-hash-map`)

**Comment by kasperisager** [comment]
Let's continue the discussion in that PR as the issue relates to Hyperswarm ☝️
